### ISSUE TITLE
[Errno 95] Operation not supported

### ISSUE THREAD

**Issue by Pharmacogenetecist** [sbslee/pypgx#122]
This looks like more a me issue, but I was hoping you could help to diagnose.

I just ran the pypgx create-input-vcf and it worked fine, but I am getting similar errors when trying to compute control statistics and depth-of-coverage.

pypgx compute-control-statistics chr12:47841537-47943048 CES_CS.zip --assembly GRCh38 "bam_ces.txt" --bed "/hg38.bed"   

    Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/pypgx/bin/pypgx", line 10, in <module>
    sys.exit(main())
  File "/home/ec2-user/anaconda3/envs/pypgx/lib/python3.7/site-packages/pypgx/__main__.py", line 33, in main
    commands[args.command].main(args)
  File "/home/ec2-user/anaconda3/envs/pypgx/lib/python3.7/site-packages/pypgx/cli/compute_control_statistics.py", line 84, in main
    result.to_file(args.control_statistics)
  File "/home/ec2-user/anaconda3/envs/pypgx/lib/python3.7/site-packages/pypgx/sdk/utils.py", line 93, in to_file
    os.path.join(t, '..')))
  File "/home/ec2-user/anaconda3/envs/pypgx/lib/python3.7/zipfile.py", line 1764, in write
    shutil.copyfileobj(src, dest, 1024*8)
  File "/home/ec2-user/anaconda3/envs/pypgx/lib/python3.7/zipfile.py", line 1172, in close
    self._fileobj.seek(self._zipfile.start_dir)
OSError: [Errno 95] Operation not supported
Exception ignored in: <function ZipFile.__del__ at 0x7f5bd95ad7a0>
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/pypgx/lib/python3.7/zipfile.py", line 1809, in __del__
    self.close()
  File "/home/ec2-user/anaconda3/envs/pypgx/lib/python3.7/zipfile.py", line 1831, in close
    self._fpclose(fp)
  File "/home/ec2-user/anaconda3/envs/pypgx/lib/python3.7/zipfile.py", line 1939, in _fpclose
    fp.close()
OSError: [Errno 95] Operation not supported

**Comment by Pharmacogenetecist** [comment]
This was a me issue, I was trying to write the files to a server directory I did not have write access to.
