### ISSUE TITLE
ImportError: cannot import name 'pycov' from 'fuc'

### ISSUE THREAD

**Issue by geocarvalho** [sbslee/pypgx#42]
Hello @sbslee, thanks for making the project available.
I have tried to install `pypgx` using your instruction but when I try to run it a still have problems with `fuc` package.

```
$ pypgx -h
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/bin/pypgx", line 33, in <module>
    sys.exit(load_entry_point('pypgx==0.10.1', 'console_scripts', 'pypgx')())
  File "/home/ubuntu/miniconda3/bin/pypgx", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/ubuntu/miniconda3/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/home/ubuntu/miniconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/pypgx/__init__.py", line 37, in <module>
    from .api.utils import (
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/pypgx/api/utils.py", line 14, in <module>
    from .. import sdk
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/pypgx/sdk/__init__.py", line 1, in <module>
    from .utils import (Archive, parse_input_bams, compare_metadata, simulate_copy_number)
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/pypgx/sdk/utils.py", line 10, in <module>
    from fuc import pyvcf, pycov, common, pybam
ImportError: cannot import name 'pycov' from 'fuc' (/home/ubuntu/miniconda3/lib/python3.8/site-packages/fuc/__init__.py)
```

Not sure about what is the problem with `fuc`.

Best,
George.

**Comment by sbslee** [comment]
@geocarvalho,

Sorry for the inconvenience. I see that you are trying to run the latest version of `pypgx` (0.10.1). What version of `fuc` are you using? The latest is 0.29.0. If you are using a lower version, please update it and try again:

```
$ conda install -c bioconda fuc=0.29.0
```

**Comment by geocarvalho** [comment]
Sorry @sbslee, it was the `fuc` version (`0.10.0`). I just had to update it.

```
$ conda install -c conda-forge matplotlib-venn
$ conda update -c bioconda fuc
```

thank you.
