### ISSUE TITLE
Error using bed 

### ISSUE THREAD

**Issue by Wilsonjsjunior** [sbslee/pypgx#61]
Hi @sbslee,
Congrats, nice work!
So, I was testing with some target data then I got that error... could you help me?

```bash
pypgx compute-control-statistics chr12:48235319-48298814 grch38-control-statistics-VDR.zip --assembly GRCh38 ../data/20210819_AHJLFMDRXY_CUSTOM_20210382/bam/*.bam --bed ../genes_pypgx.bed
Traceback (most recent call last):
  File "/Users/wilsonjunior/miniconda3/envs/pypgx/bin/pypgx", line 10, in <module>
    sys.exit(main())
  File "/Users/wilsonjunior/miniconda3/envs/pypgx/lib/python3.9/site-packages/pypgx/__main__.py", line 33, in main
    commands[args.command].main(args)
  File "/Users/wilsonjunior/miniconda3/envs/pypgx/lib/python3.9/site-packages/pypgx/cli/compute_control_statistics.py", line 81, in main
    result = utils.compute_control_statistics(
  File "/Users/wilsonjunior/miniconda3/envs/pypgx/lib/python3.9/site-packages/pypgx/api/utils.py", line 394, in compute_control_statistics
    if bam_prefix and bed_prefix:
NameError: name 'bam_prefix' is not defined
```

Thanks!!!

**Comment by sbslee** [comment]
@Wilsonjsjunior,

Thanks so much for the bug report! I was able to recreate the problem with `compute-control-statistics`. Furthermore, when I examined the code, I found the same problem in `compute-target-depth` and `prepare-depth-of-coverage` as well.

This bug is fixed in the `0.16.0-dev` branch:

```
$ git clone https://github.com/sbslee/pypgx
$ cd pypgx
$ git checkout 0.16.0-dev
$ pip install -e .
```

Thanks again for the report. Please let me know if this doesn't solve the problem. If everything works as they suppose to, I will soon release the official version of `0.16.0`.

**Comment by sbslee** [comment]
Since the bug has been fixed, I will close this issue. Please feel free to re-open it if necessary.

**Comment by Wilsonjsjunior** [comment]
Hi @sbslee,

Thanks to answer it, but I have another issue running `prepare-depth-of-coverage` using `pypgx 0.16.0`.

```
Traceback (most recent call last):
  File "/Users/wilsonjunior/miniconda3/envs/pypgx/bin/pypgx", line 33, in <module>
    sys.exit(load_entry_point('pypgx', 'console_scripts', 'pypgx')())
  File "/Users/wilsonjunior/Documents/github_wilson/pypgx/pypgx/__main__.py", line 33, in main
    commands[args.command].main(args)
  File "/Users/wilsonjunior/Documents/github_wilson/pypgx/pypgx/cli/prepare_depth_of_coverage.py", line 90, in main
    archive = utils.prepare_depth_of_coverage(
  File "/Users/wilsonjunior/Documents/github_wilson/pypgx/pypgx/api/utils.py", line 1241, in prepare_depth_of_coverage
    if bam_prefix and bed_prefix:
NameError: name 'bam_prefix' is not defined
```

thanks!!!

**Comment by sbslee** [comment]
@Wilsonjsjunior,

That's strange! As mentioned previously, the bug has been fixed for the three methods: `api.utils.compute_control_statistics`, `api.utils.compute_target_depth`, and `api.utils.prepare_depth_of_coverage`.

For example, there is no variable named `bam_prefix` at all in `api.utils.prepare_depth_of_coverage`.

https://github.com/sbslee/pypgx/blob/74d5c14f5dd3b6cabfd50008d758390133d17c80/pypgx/api/utils.py#L1179-L1241

Could you please try again by installing the official release of `0.16.0` in a fresh conda environment?

```
$ conda create -n pypgx -c bioconda pypgx=0.16.0 fuc=0.34.0
$ conda activate pypgx
```
