### ISSUE TITLE
Improve PyPGx's handling of genes on X chromosome (i.e. G6PD) 

### ISSUE THREAD

**Issue by sbslee** [sbslee/pypgx#64]
A PyPGx user recently reported the following via email:

G6PD x-chr single allele case?

For this one, I'm also attaching a sample G6PD vcf I tried running with run_ngs_pipeline()
The error I get is something like this:
```
❯ pypgx run-ngs-pipeline --variants G6PD.ref.fixed.vcf.gz --panel /mnt/data/pypgx-bundle/1kgp/GRCh37/G6PD.vcf.gz G6PD /tmp/pypgx-g6pd-ukb

Saved VcfFrame[Imported] to: /tmp/pypgx-g6pd-ukb/imported-variants.zip
Saved VcfFrame[Phased] to: /tmp/pypgx-g6pd-ukb/phased-variants.zip
Saved VcfFrame[Consolidated] to: /tmp/pypgx-g6pd-ukb/consolidated-variants.zip
```

```
Traceback (most recent call last):
  File "/home/min/venv/mg/bin/pypgx", line 8, in <module>
    sys.exit(main())
  File "/home/min/venv/mg/lib/python3.8/site-packages/pypgx/__main__.py", line 33, in main
    commands[args.command].main(args)
  File "/home/min/venv/mg/lib/python3.8/site-packages/pypgx/cli/run_ngs_pipeline.py", line 159, in main
    pipeline.run_ngs_pipeline(
  File "/home/min/venv/mg/lib/python3.8/site-packages/pypgx/api/pipeline.py", line 247, in run_ngs_pipeline
    alleles = utils.predict_alleles(consolidated_variants)
  File "/home/min/venv/mg/lib/python3.8/site-packages/pypgx/api/utils.py", line 1109, in predict_alleles
    observed = consolidated_variants.data.df.apply(one_row, args=(sample, i), axis=1)
  File "/home/min/venv/mg/lib/python3.8/site-packages/pandas/core/frame.py", line 8740, in apply
    return op.apply()
  File "/home/min/venv/mg/lib/python3.8/site-packages/pandas/core/apply.py", line 688, in apply
    return self.apply_standard()
  File "/home/min/venv/mg/lib/python3.8/site-packages/pandas/core/apply.py", line 812, in apply_standard
    results, res_index = self.apply_series_generator()
  File "/home/min/venv/mg/lib/python3.8/site-packages/pandas/core/apply.py", line 828, in apply_series_generator
    results[i] = self.f(v)
  File "/home/min/venv/mg/lib/python3.8/site-packages/pandas/core/apply.py", line 131, in f
    return func(x, *args, **kwargs)
  File "/home/min/venv/mg/lib/python3.8/site-packages/pypgx/api/utils.py", line 1086, in one_row
    j = int(gt.split('|')[i])
IndexError: list index out of range
```

I ran this using the CLI version, just to rule out any api integration mistakes. Looking at utils.py it does assume that gt has two alleles. In the case of G6PD x-chromosome data, doesn't that break the assumption? Not my area, so correct me if I'm wrong about this. Either way, I'm hoping you can reproduce the errors using the sample files I'm sending over.

**Comment by sbslee** [comment]
This was my initial response:

This is a known issue for G6PD. Depending on which variant caller you use (e.g. GATK, BCFtools), you can get two different genotype representations for males (e.g. '0/1' vs. '1'). FYI, PyPGx internally uses BCFtools to call variants (i.e. the create-input-vcf command) and it returns the diploid representation even for males. However, since I know other variant callers can return the haplotype representation (like yours), I will think about ways to handle this kind of situation better.

The reason PyPGx does not require sex information from VCF is because it can identify sex from copy number data (see https://pypgx.readthedocs.io/en/latest/genes.html#g6pd).

**Comment by sbslee** [comment]
I've updated `api.utils.import_variants` to 'diploidize' the input VCF when the target gene is G6PD. Basically, this will convert haploid genotypes to diploid genotypes (e.g. `1` to `0/1`). Of course, this will assume all samples are female, but you can always provide read depth data to account for sex (see [here](https://pypgx.readthedocs.io/en/latest/genes.html#sv-summary-for-g6pd) for more details).

With this update, your previous command works just fine:

```
$ pypgx run-ngs-pipeline \
G6PD \
G6PD-pipeline \
--variants G6PD.ref.fixed.vcf.gz \
--do-not-plot-allele-fraction
Saved VcfFrame[Imported] to: G6PD-pipeline/imported-variants.zip
Saved VcfFrame[Phased] to: G6PD-pipeline/phased-variants.zip
Saved VcfFrame[Consolidated] to: G6PD-pipeline/consolidated-variants.zip
Saved SampleTable[Alleles] to: G6PD-pipeline/alleles.zip
/Users/sbslee/Desktop/pypgx/pypgx/api/genotype.py:665: UserWarning: The user did not provide CNV calls even though the target gene is known to have SV. PyPGx will assume all of the samples do not have SV.
  warnings.warn(message)
Saved SampleTable[Genotypes] to: G6PD-pipeline/genotypes.zip
Saved SampleTable[Phenotypes] to: G6PD-pipeline/phenotypes.zip
Saved SampleTable[Results] to: G6PD-pipeline/results.zip
```

P.S. I'm still pondering about the best way to carry the sex information encoded in the input VCF (e.g. `1` vs. `0/1`) all the way to the genotyping step (i.e. dropping the requirement of read depth data for sex determination). However, this turned out to be more difficult than I originally anticipated... :(

**Comment by sbslee** [comment]
Closing this. Please feel free to re-open it if necessary.

**Comment by sbslee** [comment]
Oops, I forgot to mention that this update is made in the latest branch of pypgx `0.17.0-dev`. Also, it requires the latest version of fuc `0.35.0-dev`.
