### ISSUE TITLE
Why running my WGS data stops in the middle?

### ISSUE THREAD

**Issue by sbargal1** [sbslee/pypgx#66]
![image](https://user-images.githubusercontent.com/61886850/174156014-5c65d47e-e4c1-4730-b02e-2552a4a7a702.png)

Hello,

As seen in the attached image, I have run the code for WGS and it ran and then stopped with the above error:

Here is my code:

```
/usr/local/packages/python-3.9.13/bin/pypgx run-ngs-pipeline CYP2C19 /data4/sbargal/Amish/results/WGS/pypgx/CYP2C19 --variants /data4/sbargal/Amish/amish_input_data/build38/TOPMed6a_build38_889_subject_vcf.vcf.gz --assembly GRCh38 --panel /data4/sbargal/Amish/amish_input_data/build38/resource_bundle/pypgx-bundle/1kgp/GRCh38/CYP2C19.vcf.gz
```

Here is the error:

```
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-lmw_btrn because the default path (/home/sbargal/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Saved VcfFrame[Imported] to: /data4/sbargal/Amish/results/WGS/pypgx/CYP2C19/imported-variants.zip
Traceback (most recent call last):
  File "/usr/local/packages/python-3.9.13/bin/pypgx", line 8, in <module>
    sys.exit(main())
  File "/usr/local/packages/python-3.9.13/lib/python3.9/site-packages/pypgx/__main__.py", line 33, in main
    commands[args.command].main(args)
  File "/usr/local/packages/python-3.9.13/lib/python3.9/site-packages/pypgx/cli/run_ngs_pipeline.py", line 159, in main
    pipeline.run_ngs_pipeline(
  File "/usr/local/packages/python-3.9.13/lib/python3.9/site-packages/pypgx/api/pipeline.py", line 239, in run_ngs_pipeline
    phased_variants = utils.estimate_phase_beagle(
  File "/usr/local/packages/python-3.9.13/lib/python3.9/site-packages/pypgx/api/utils.py", line 851, in estimate_phase_beagle
    subprocess.run(command, check=True, stdout=subprocess.DEVNULL)
  File "/usr/local/packages/python-3.9.13/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['java', '-Xmx2g', '-jar', '/usr/local/packages/python-3.9.13/lib/python3.9/site-packages/pypgx/api/beagle.28Jun21.220.jar', 'gt=/tmp/tmp42k2isct/input.vcf', 'chrom=chr10:94759680-94858547', 'ref=/data4/sbargal/Amish/amish_input_data/build38/resource_bundle/pypgx-bundle/1kgp/GRCh38/CYP2C19.vcf.gz', 'out=/tmp/tmp42k2isct/output', 'impute=false']' returned non-zero exit status 1.
```

I would appreciate it if you could help me handle this error so I can proceed with the next step.

Thank you

Best Regards,

Salma

**Comment by sbslee** [comment]
@sbargal1,

Thanks for your interest in using PyPGx.

1. What is your OS (i.e. Windows vs. macOS vs. Linux)?

2. Which PyPGx version are you using?

3. How did you install PyPGx (i.e. `pip` vs. `conda` vs. local)?

4. Did you install Java JDK (e.g. `openjdk`) in your PyPGx environment?

5. Can you send me your input VCF file (`TOPMed6a_build38_889_subject_vcf.vcf.gz`) at sbstevenlee@gmail.com so I can try to recreate the problem? I see that it's from TOPMed which may be too large for transfer. All I need is some materials to recreate the problem; therefore, you can slice the VCF so that it contains only a few samples.

P.S. You don't need to specify the `--panel` argument if you are going to use the reference panel provided by PyPGx. It will automatically access it. This argument is meant to be used when the user has their own reference panel.

**Comment by sbslee** [comment]
As for 5., on second thought, if you prefer, you can send `imported-variants.zip` instead of `TOPMed6a_build38_889_subject_vcf.vcf.gz`.

**Comment by sbargal1** [comment]
1. Red Hat Enterprise Linux release 8.3 (Ootpa)

2. pypgx 0.15.0

3. pip

4. Not sure, all we did to install was “pip install pypgx”. We used python 3.9.13

5. I'll send you a sample of vcf used


We need to specify –panel because the location of the files is different from where pypgx expects the files to be.

Thanks for your prompt reply.

I also had a q regarding the test data is it WGS or chip data? I wanted to try to run an example of WGS.

**Comment by sbslee** [comment]
@sbargal1,

As explained in the [Installation](https://pypgx.readthedocs.io/en/latest/readme.html#installation) section, if you've only installed PyPGx via `pip`, then the problem is most likely caused because you don't have Java JDK at all or you are using an outdated version of it. In your working environment, can you show me the output of:

```
$ javac -version
```

The output should look something like this:

```
$ javac -version
javac 1.8.0_92
```

If the output looks like this:

```
$ javac -version
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.
```

Then you need to download and install Java JDK (see [here](https://access.redhat.com/documentation/en-us/openjdk/8/html-single/installing_and_using_openjdk_8_for_rhel/index)).

> We need to specify –panel because the location of the files is different from where pypgx expects the files to be.

That makes sense.

> I also had a q regarding the test data is it WGS or chip data? I wanted to try to run an example of WGS.

There are currently two tutorials, [this one](https://pypgx.readthedocs.io/en/latest/tutorials.html#get-rm-wgs-tutorial) for WGS data and [this one](https://pypgx.readthedocs.io/en/latest/tutorials.html#coriell-affy-tutorial) for chip data.

**Comment by sbargal1** [comment]
![image](https://user-images.githubusercontent.com/61886850/174451462-ec5eff48-c1a9-45bb-ae6c-e81f170dd303.png)

As in the picture above, it seems that Java is installed. Is the version ok?

**Comment by sbslee** [comment]
> it seems that Java is installed. Is the version ok?

Yes, it appears Java JDK wasn't the problem after all.

To recreate your issue, I saved the VCF data you sent me via email to a file ([in.vcf.gz](https://github.com/sbslee/pypgx/files/8934774/in.vcf.gz)) and then ran the same PyPGx version (`0.15.0`), and it worked fine. See the attached results: [CYP2C19-pipeline.tar.gz](https://github.com/sbslee/pypgx/files/8934707/CYP2C19-pipeline.tar.gz). I used the following command:

```
$ pypgx run-ngs-pipeline \
CYP2C19 \
CYP2C19-pipeline \
--variants in.vcf.gz \
--assembly GRCh38 \
--do-not-plot-allele-fraction \
--force
```

Q1. Can you verify that you can reproduce the same error with the example dataset (i.e. `in.vcf.gz`), even though I can't? When I looked at the VCF data, there were 10 samples and 71 variants in chromosome 1, but all of the genotypes were missing (i.e. `./.`). Plus, the CYP2C19 gene is located in chromosome 10, not 1.

Q2. Are you able to follow the [WGS tutorial](https://pypgx.readthedocs.io/en/latest/tutorials.html#get-rm-wgs-tutorial)?

Q3. Can you send me the file `/data4/sbargal/Amish/results/WGS/pypgx/CYP2C19/imported-variants.zip`?

Q4. Your issue may be related to #63 whose bug has been fixed in the latest development version of PyPGx (`0.17.0-dev`). You can try it to see if the problem goes away with the fix:

```
$ git clone https://github.com/sbslee/pypgx
$ cd pypgx
$ git checkout 0.17.0-dev
$ pip install .
```

**Comment by sbargal1** [comment]
It seems like it ran for sample data (please see below) but did not for the whole data file

```
[sbargal@lendl pypgx]$ /usr/local/packages/python-3.9.13/bin/pypgx run-ngs-pipeline CYP2C19 /data4/sbargal/Amish/results/WGS/pypgx/CYP2C19_3 --variants /data4/sbargal/Amish/amish_input_data/build38/Sample_data.in.vcf.gz --assembly GRCh38 --do-not-plot-allele-fraction --force --panel /data4/sbargal/Amish//amish_input_data//build38/resource_bundle/pypgx-bundle/1kgp/GRCh38/CYP2C19.vcf.gz
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-7g3md8qt because the default path (/home/sbargal/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=1,length=248946421>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=2,length=242183450>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=3,length=198232941>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=4,length=190204549>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=5,length=181478116>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=6,length=170744807>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=7,length=159335971>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=8,length=145078175>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=9,length=138334547>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=10,length=133787419>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=11,length=135076616>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=12,length=133264930>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=13,length=114354152>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=14,length=106883659>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=15,length=101981163>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=16,length=90228325>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=17,length=83247422>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=18,length=80263281>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=19,length=58607594>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=20,length=64334014>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=21,length=46699979>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=22,length=50808374>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=23,length=156030803>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[E::bcf_hdr_parse_line] Could not parse the header line: "##INFO=<ID=PR,Number=0,Type=Flag,Description=\"\"Provisional reference allele, may not be based on real reference genome\"\">\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"
[E::bcf_hdr_parse_line] Could not parse the header line: "##FORMAT=<ID=GT,Number=1,Type=String,Description=\"\"Genotype\"\">\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"
[W::vcf_parse_info] INFO 'PR' is not defined in the header, assuming Type=String
[W::vcf_parse_format] FORMAT 'GT' at 1:10128 is not defined in the header, assuming Type=String
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=1,length=248946421>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=2,length=242183450>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=3,length=198232941>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=4,length=190204549>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=5,length=181478116>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=6,length=170744807>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=7,length=159335971>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=8,length=145078175>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=9,length=138334547>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=10,length=133787419>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=11,length=135076616>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=12,length=133264930>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=13,length=114354152>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=14,length=106883659>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=15,length=101981163>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=16,length=90228325>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=17,length=83247422>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=18,length=80263281>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=19,length=58607594>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=20,length=64334014>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=21,length=46699979>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=22,length=50808374>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[W::bcf_hdr_parse_line] Dropped trailing junk from header line '"##contig=<ID=23,length=156030803>\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"'
[E::bcf_hdr_parse_line] Could not parse the header line: "##INFO=<ID=PR,Number=0,Type=Flag,Description=\"\"Provisional reference allele, may not be based on real reference genome\"\">\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"
[E::bcf_hdr_parse_line] Could not parse the header line: "##FORMAT=<ID=GT,Number=1,Type=String,Description=\"\"Genotype\"\">\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"
Saved VcfFrame[Imported] to: /data4/sbargal/Amish/results/WGS/pypgx/CYP2C19_3/imported-variants.zip
Saved VcfFrame[Phased] to: /data4/sbargal/Amish/results/WGS/pypgx/CYP2C19_3/phased-variants.zip
/usr/local/packages/python-3.9.13/lib/python3.9/site-packages/fuc/api/pyvcf.py:5276: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  df = self.df.sort_values(by=['CHROM', 'POS'], ignore_index=True,
Saved VcfFrame[Consolidated] to: /data4/sbargal/Amish/results/WGS/pypgx/CYP2C19_3/consolidated-variants.zip
Saved SampleTable[Alleles] to: /data4/sbargal/Amish/results/WGS/pypgx/CYP2C19_3/alleles.zip
Saved SampleTable[Genotypes] to: /data4/sbargal/Amish/results/WGS/pypgx/CYP2C19_3/genotypes.zip
Saved SampleTable[Phenotypes] to: /data4/sbargal/Amish/results/WGS/pypgx/CYP2C19_3/phenotypes.zip
Saved SampleTable[Results] to: /data4/sbargal/Amish/results/WGS/pypgx/CYP2C19_3/results.zip
```

**Comment by sbslee** [comment]
@sbargal1,

> It seems like it ran for sample data (please see below) but did not for the whole data file

In order to help you, I need a minimal test file which I can use to reproduce the exact issue. Since your sample data reproduced the error for neither of us, I will need a different test file.

Alternatively, if you still have the file `/data4/sbargal/Amish/results/WGS/pypgx/CYP2C19/imported-variants.zip`, you can send it to me so I can do some diagnosis with it (this was Q3 from my previous post).

Also see Q2 and Q4 above.

**Comment by sbargal1** [comment]
Q2. Yes we followed the instructions for genotyping genes without SV. However, I did not download the data in the tutorial. I used our data straightaway.

I was waiting to see with our group if we can send this file over that is why it was not addressed earlier.

Q3. Sent

Q4. That will be our last resort if it did not work out.

Thanks

Salma

**Comment by sbslee** [comment]
@sbargal1,

I believe I found the problem: Your VCF does not have ALT alleles at all (it only contains REF alleles) and this is true for both of the files you have sent me.

The last sample VCF did not raise any errors because it did not contain any CYP2C19 variants and therefore it was equivalent to an empty VCF, which is supported by PyPGx.

I was able to reproduce the same error as you did with `imported-variants.zip`, but upon the closer look I realized that it was missing ALT alleles. Same was true for the last VCF file.

Please make sure your VCF was correctly generated.

**Comment by sbargal1** [comment]
Thanks for spotting this!
Ok we fixed the file and it ran more than the previous one but still stopped:

```
[sbargal@lendl pypgx]$ /usr/local/packages/python-3.9.13/bin/pypgx run-ngs-pipeline CYP2C19 /data4/sbargal/Amish/results/WGS/pypgx/CYP2C19_whole_data_corrected --variants /data4/sbargal/Amish/amish_input_data/build38/TOPMed6a_build38_889_subjects_try2correctnoGTissue_vcf.vcf.gz --assembly GRCh38 --do-not-plot-allele-fraction --force --panel /data4/sbargal/Amish/amish_input_data/build38/resource_bundle/pypgx-bundle/1kgp/GRCh38/CYP2C19.vcf.gz
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-pccgwzrc because the default path (/home/sbargal/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Saved VcfFrame[Imported] to: /data4/sbargal/Amish/results/WGS/pypgx/CYP2C19_whole_data_corrected/imported-variants.zip
Saved VcfFrame[Phased] to: /data4/sbargal/Amish/results/WGS/pypgx/CYP2C19_whole_data_corrected/phased-variants.zip
Traceback (most recent call last):
  File "/usr/local/packages/python-3.9.13/bin/pypgx", line 8, in <module>
    sys.exit(main())
  File "/usr/local/packages/python-3.9.13/lib/python3.9/site-packages/pypgx/__main__.py", line 33, in main
    commands[args.command].main(args)
  File "/usr/local/packages/python-3.9.13/lib/python3.9/site-packages/pypgx/cli/run_ngs_pipeline.py", line 159, in main
    pipeline.run_ngs_pipeline(
  File "/usr/local/packages/python-3.9.13/lib/python3.9/site-packages/pypgx/api/pipeline.py", line 242, in run_ngs_pipeline
    consolidated_variants = utils.create_consolidated_vcf(
  File "/usr/local/packages/python-3.9.13/lib/python3.9/site-packages/pypgx/api/utils.py", line 632, in create_consolidated_vcf
    vf6 = _phase_extension(vf5, gene, assembly)
  File "/usr/local/packages/python-3.9.13/lib/python3.9/site-packages/pypgx/api/utils.py", line 55, in _phase_extension
    gt = r[sample].split(':')[0]
AttributeError: 'float' object has no attribute 'split'
```

**Comment by sbslee** [comment]
I will need both `imported-variants.zip` and `phased-variants.zip` to know for sure what happened, but it looks like there are still some problems in your input VCF. The error is complaining that there is no `GT` field in sample genotype calls (e.g. `0.242` instead of `0/1:0.242`). Please check your VCF again and make sure it has `GT` filed (`0/1`, `1/1`, etc.). Also you can send me those files and I'd be happy to take a look.

BTW, how are you generating your VCF? If you have BAM files for WGS data, the best way to produce input VCF for PyPGx is to use `$ pypgx create-input-vcf`.

**Comment by sbargal1** [comment]
I have sent you both zipped files. As for how we generate VCF files, we have bcf files for each chromosome that we take to plink, merge plink files, and output to vcf. We had to take the files to plink first before going to vcf because of a snp name and to fix the original issue we had with no alt alleles

**Comment by sbslee** [comment]
I found the problem from `imported-variants.zip`: Your VCF contains two entries (i.e. rows) for the identical variant `10-94842393-G-GT`. Worsening the situation, some samples have different genotype calls. For instance, the first sample has `0/0` for the first row while `1/1` for the second row. Even if I wanted to update PyPGx to handle these apparently redundant variants, because their genotypes are different, I can't.

This type of situation usually indicates that something went wrong in the upstream analysis. Since you already have BCF files, couldn't you simply convert them to VCF using `$ bcftools convert` (see [here](http://samtools.github.io/bcftools/bcftools.html#convert) and [here](https://www.biostars.org/p/9495084/))?

Please remove redundant variants and then try running PyPGx again.

**Comment by sbslee** [comment]
@sbargal1,

I "fixed" your input VCF by removing the second record of `10-94842393-G-GT`, and was able to run PyPGx. I sent the files to you via email.

```
$ pypgx run-ngs-pipeline \
CYP2C19 \
CYP2C19-pipeline \
--variants fixed.vcf.gz \
--assembly GRCh38 \
--do-not-plot-allele-fraction \
--force
[W::vcf_parse_format] FORMAT 'GT' at 10:94759934 is not defined in the header, assuming Type=String
[W::vcf_parse_format] FORMAT 'AD' at 10:94759934 is not defined in the header, assuming Type=String
[W::vcf_parse_format] FORMAT 'DP' at 10:94759934 is not defined in the header, assuming Type=String
[W::vcf_parse_format] FORMAT 'AF' at 10:94759934 is not defined in the header, assuming Type=String
[W::vcf_parse_format] FORMAT 'GT' at 10:94759934 is not defined in the header, assuming Type=String
[W::vcf_parse_format] FORMAT 'AD' at 10:94759934 is not defined in the header, assuming Type=String
[W::vcf_parse_format] FORMAT 'DP' at 10:94759934 is not defined in the header, assuming Type=String
[W::vcf_parse_format] FORMAT 'AF' at 10:94759934 is not defined in the header, assuming Type=String
Saved VcfFrame[Imported] to: CYP2C19-pipeline/imported-variants.zip
Saved VcfFrame[Phased] to: CYP2C19-pipeline/phased-variants.zip
Saved VcfFrame[Consolidated] to: CYP2C19-pipeline/consolidated-variants.zip
Saved SampleTable[Alleles] to: CYP2C19-pipeline/alleles.zip
Saved SampleTable[Genotypes] to: CYP2C19-pipeline/genotypes.zip
Saved SampleTable[Phenotypes] to: CYP2C19-pipeline/phenotypes.zip
Saved SampleTable[Results] to: CYP2C19-pipeline/results.zip
```

**Comment by sbslee** [comment]
Closing this since the original issue has been addressed. Please feel free to re-open it if necessary.
