### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Pharmacogenetecist** [sbslee/pypgx#74]
Hello there, I am working in a new compute environment and get the following error after installation.

```
(PYPGX) pypgx --help
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/PYPGX/bin/pypgx", line 6, in <module>
    from pypgx.__main__ import main
  File "/home/ec2-user/anaconda3/envs/PYPGX/lib/python3.7/site-packages/pypgx/__init__.py", line 1, in <module>
    from .api.core import (
  File "/home/ec2-user/anaconda3/envs/PYPGX/lib/python3.7/site-packages/pypgx/api/core.py", line 10, in <module>
    from .. import sdk
  File "/home/ec2-user/anaconda3/envs/PYPGX/lib/python3.7/site-packages/pypgx/sdk/__init__.py", line 1, in <module>
    from .utils import (Archive, add_cn_samples, compare_metadata, simulate_copy_number)
  File "/home/ec2-user/anaconda3/envs/PYPGX/lib/python3.7/site-packages/pypgx/sdk/utils.py", line 10, in <module>
    from fuc import pyvcf, pycov, common, pybam
  File "/home/ec2-user/anaconda3/envs/PYPGX/lib/python3.7/site-packages/fuc/__init__.py", line 1, in <module>
    from .api import *
  File "/home/ec2-user/anaconda3/envs/PYPGX/lib/python3.7/site-packages/fuc/api/common.py", line 19, in <module>
    from . import pyvcf
  File "/home/ec2-user/anaconda3/envs/PYPGX/lib/python3.7/site-packages/fuc/api/pyvcf.py", line 146, in <module>
    from . import pybed, common, pymaf, pybam
  File "/home/ec2-user/anaconda3/envs/PYPGX/lib/python3.7/site-packages/fuc/api/pymaf.py", line 61, in <module>
    import statsmodels.formula.api as smf
  File "/home/ec2-user/anaconda3/envs/PYPGX/lib/python3.7/site-packages/statsmodels/formula/api.py", line 15, in <module>
    from statsmodels.discrete.discrete_model import MNLogit
  File "/home/ec2-user/anaconda3/envs/PYPGX/lib/python3.7/site-packages/statsmodels/discrete/discrete_model.py", line 45, in <module>
    from statsmodels.distributions import genpoisson_p
  File "/home/ec2-user/anaconda3/envs/PYPGX/lib/python3.7/site-packages/statsmodels/distributions/__init__.py", line 2, in <module>
    from .edgeworth import ExpandedNormal
  File "/home/ec2-user/anaconda3/envs/PYPGX/lib/python3.7/site-packages/statsmodels/distributions/edgeworth.py", line 7, in <module>
    from scipy.misc import factorial
ImportError: cannot import name 'factorial' from 'scipy.misc' (/home/ec2-user/anaconda3/envs/PYPGX/lib/python3.7/site-packages/scipy/misc/__init__.py)
```

**Comment by sbslee** [comment]
@Pharmacogenetecist,

The problem seems to be caused by the version mismatch between the `statsmodels` package and the `scipy` package (i.e. it's not a PyPGx issue). You're also using a relatively lower version of Python (3.7). Can you create a freshly new environment using:

```
$ conda create -n test -c bioconda pypgx==0.19.0 fuc==0.36.0
```

**Comment by Pharmacogenetecist** [comment]
> conda create -n test -c bioconda pypgx==0.19.0 fuc==0.36.0

Thank you, I appreciate you getting back to me. Which Python version would you suggest I update to?

I tried the above and got a similar error:

```
(test) pypgx --help
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/test/bin/pypgx", line 6, in <module>
    from pypgx.__main__ import main
  File "/home/ec2-user/anaconda3/envs/test/lib/python3.7/site-packages/pypgx/__init__.py", line 1, in <module>
    from .api.core import (
  File "/home/ec2-user/anaconda3/envs/test/lib/python3.7/site-packages/pypgx/api/core.py", line 10, in <module>
    from .. import sdk
  File "/home/ec2-user/anaconda3/envs/test/lib/python3.7/site-packages/pypgx/sdk/__init__.py", line 1, in <module>
    from .utils import (Archive, add_cn_samples, compare_metadata, simulate_copy_number)
  File "/home/ec2-user/anaconda3/envs/test/lib/python3.7/site-packages/pypgx/sdk/utils.py", line 10, in <module>
    from fuc import pyvcf, pycov, common, pybam
  File "/home/ec2-user/anaconda3/envs/test/lib/python3.7/site-packages/fuc/__init__.py", line 1, in <module>
    from .api import *
  File "/home/ec2-user/anaconda3/envs/test/lib/python3.7/site-packages/fuc/api/common.py", line 19, in <module>
    from . import pyvcf
  File "/home/ec2-user/anaconda3/envs/test/lib/python3.7/site-packages/fuc/api/pyvcf.py", line 146, in <module>
    from . import pybed, common, pymaf, pybam
  File "/home/ec2-user/anaconda3/envs/test/lib/python3.7/site-packages/fuc/api/pymaf.py", line 61, in <module>
    import statsmodels.formula.api as smf
  File "/home/ec2-user/anaconda3/envs/test/lib/python3.7/site-packages/statsmodels/formula/api.py", line 15, in <module>
    from statsmodels.discrete.discrete_model import MNLogit
  File "/home/ec2-user/anaconda3/envs/test/lib/python3.7/site-packages/statsmodels/discrete/discrete_model.py", line 45, in <module>
    from statsmodels.distributions import genpoisson_p
  File "/home/ec2-user/anaconda3/envs/test/lib/python3.7/site-packages/statsmodels/distributions/__init__.py", line 2, in <module>
    from .edgeworth import ExpandedNormal
  File "/home/ec2-user/anaconda3/envs/test/lib/python3.7/site-packages/statsmodels/distributions/edgeworth.py", line 7, in <module>
    from scipy.misc import factorial
ImportError: cannot import name 'factorial' from 'scipy.misc' (/home/ec2-user/anaconda3/envs/test/lib/python3.7/site-packages/scipy/misc/__init__.py)
```

**Comment by sbslee** [comment]
@Pharmacogenetecist,

That's weird! Can you show me the output of `$ conda list` at your `test` conda environment? The error suggests that you are still installing a very old version of `statsmodels` (the latest version is v0.13.2). See this SO [post](https://stackoverflow.com/questions/56283294/importerror-cannot-import-name-factorial).

Also, I've noticed that an old version of Python (v3.7) was installed again in your new environment. There is nothing wrong with Python 3.7 per se, but it will definitely restrict the number of Python packages that can be installed to your environment because most of these packages will require a higher Python version for their latest releases. PyPGx doesn't have a specific Python version requirement, but I'm currently using Python 3.9.7, for example.

That being said, have you set your conda configuration yet? See my [post](https://sbslee-notes.readthedocs.io/en/latest/anaconda.html#package-management-for-r) for details. Setting your conda configuration will save a ton of your time:

```
$ conda config --add channels defaults
$ conda config --add channels bioconda
$ conda config --add channels conda-forge
```

This ensures that you are installing packages from intended channels. Run above first before installing again:

```
$ conda create -n test -c bioconda pypgx==0.19.0 fuc==0.36.0
```

See if this fixes the problem. If it doesn't, please attach the output of `$ conda list` as well.

**Comment by Pharmacogenetecist** [comment]
Thanks for your response! The conda configuration must have fixed it,
pypgx -h  works now. Appreciate your help and the extra information.
