### ISSUE TITLE
Depth of coverage command.

### ISSUE THREAD

**Issue by Pharmacogenetecist** [sbslee/pypgx#75]
I am using some exome data to see what kind of 2D6 data I can pull. Following the tutorial I guess I need a depth of coverage file which I tried to create, but am getting the following impressive error.

```
(test) pypgx prepare-depth-of-coverage depth-of-coverage.zip --assembly GRCh38 "/home/ec2-user/bams.txt" --bed "/home/ec2-user/DATA/agilentV6_design_hg38.bed"
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/test/bin/pypgx", line 10, in <module>
    sys.exit(main())
  File "/home/ec2-user/anaconda3/envs/test/lib/python3.7/site-packages/pypgx/__main__.py", line 33, in main
    commands[args.command].main(args)
  File "/home/ec2-user/anaconda3/envs/test/lib/python3.7/site-packages/pypgx/cli/prepare_depth_of_coverage.py", line 92, in main
    exclude=args.exclude
  File "/home/ec2-user/anaconda3/envs/test/lib/python3.7/site-packages/pypgx/api/utils.py", line 1275, in prepare_depth_of_coverage
    cf = pycov.CovFrame.from_bam(bams, regions=regions, zero=True)
  File "/home/ec2-user/anaconda3/envs/test/lib/python3.7/site-packages/fuc/api/pycov.py", line 315, in from_bam
    if all([pybam.has_chr_prefix(x) for x in bams]):
  File "/home/ec2-user/anaconda3/envs/test/lib/python3.7/site-packages/fuc/api/pycov.py", line 315, in <listcomp>
    if all([pybam.has_chr_prefix(x) for x in bams]):
  File "/home/ec2-user/anaconda3/envs/test/lib/python3.7/site-packages/fuc/api/pybam.py", line 187, in has_chr_prefix
    contigs = tag_sn(fn)
  File "/home/ec2-user/anaconda3/envs/test/lib/python3.7/site-packages/fuc/api/pybam.py", line 163, in tag_sn
    lines = pysam.view('-H', fn, '--no-PG').strip().split('\n')
  File "/home/ec2-user/anaconda3/envs/test/lib/python3.7/site-packages/pysam/utils.py", line 75, in __call__
    stderr))
pysam.utils.SamtoolsError: "samtools returned with error 1: stdout=, stderr=samtools view: unrecognised option '--no-PG'\n\nUsage: samtools view [options] <in.bam>|<in.sam>|<in.cram> [region ...]\n\nOptions:\n  -b       output BAM\n  -C       output CRAM (requires -T)\n  -1       use fast BAM compression (implies -b)\n  -u       uncompressed BAM output (implies -b)\n  -h       include header in SAM output\n  -H       print SAM header only (no alignments)\n  -c       print only the count of matching records\n  -o FILE  output file name [samtools_stdout]\n  -U FILE  output reads not selected by filters to FILE [null]\n  -t FILE  FILE listing reference names and lengths (see long help) [null]\n  -L FILE  only include reads overlapping this BED FILE [null]\n  -r STR   only include reads in read group STR [null]\n  -R FILE  only include reads with read group listed in FILE [null]\n  -q INT   only include reads with mapping quality >= INT [0]\n  -l STR   only include reads in library STR [null]\n  -m INT   only include reads with number of CIGAR operations consuming\n           query sequence >= INT [0]\n  -f INT   only include reads with all  of the FLAGs in INT present [0]\n  -F INT   only include reads with none of the FLAGS in INT present [0]\n  -G INT   only EXCLUDE reads with all  of the FLAGs in INT present [0]\n  -s FLOAT subsample reads (given INT.FRAC option value, 0.FRAC is the\n           fraction of templates/read pairs to keep; INT part sets seed)\n  -M       use the multi-region iterator (increases the speed, removes\n           duplicates and outputs the reads as they are ordered in the file)\n  -x STR   read tag to strip (repeatable) [null]\n  -B       collapse the backward CIGAR operation\n  -?       print long help, including note about region specification\n  -S       ignored (input format is auto-detected)\n      --input-fmt-option OPT[=VAL]\n               Specify a single input file format option in the form\n               of OPTION or OPTION=VALUE\n  -O, --output-fmt FORMAT[,OPT[=VAL]]...\n               Specify output format (SAM, BAM, CRAM)\n      --output-fmt-option OPT[=VAL]\n               Specify a single output file format option in the form\n               of OPTION or OPTION=VALUE\n  -T, --reference FILE\n               Reference sequence FASTA FILE [null]\n  -@, --threads INT\n               Number of additional threads to use [0]\n\n"
```

**Comment by sbslee** [comment]
@Pharmacogenetecist,

This error seems to be caused due to having a low version of `pysam`. What's the version you are using? Can you try again after installing a newer version (e.g. `0.19.0`) in the `test` environment?

```
$ conda install pysam==0.19.0
```

**Comment by Pharmacogenetecist** [comment]
> conda install pysam==0.19.0

Thank you! That resolved the issue.
