### ISSUE TITLE
Window has only one position error" happened when running Estimate-phase-beagle with variants.

### ISSUE THREAD

**Issue by leefall** [sbslee/pypgx#80]
Dear sbslee,

I found that the window has only one position error that happened with the below variant when I ran Estimate-phase-beagle for CYP2W1 gene.

*metadata.txt
Platform=WGS
Gene=CYP2W1
Assembly=GRCh37
SemanticType=VcfFrame[Imported]

*data.vcf
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  971
7       1020320 .       CT      C       .       .       .       GT:AD:DP:AF     0/1:3,13:16:0.188,0.812
7       1028279 .       G       A       .       .       .       GT:AD:DP:AF     0/1:16,16:32:0.500,0.500
7       1029860 .       T       C       .       .       .       GT:AD:DP:AF     0/1:6,4:10:0.600,0.400
7       1032032 .       C       G       .       .       .       GT:AD:DP:AF     0/1:20,17:37:0.541,0.459

As you see, the two variants (7:1028279G>A and 7:1032032C>G) are included in window size ('chrom=7:1019834-1032276') and overlapped with 1kgp/GRCh37/CYP2W1.vcf.gz.

However, the error message was printed as follow.

Exception in thread "main" java.lang.IllegalArgumentException: Window has only one position: CHROM=7 POS=1028279
	at vcf.MarkerMap.meanSingleBaseGenDist(MarkerMap.java:98)
	at phase.FixedPhaseData.markerMap(FixedPhaseData.java:170)
	at phase.FixedPhaseData.<init>(FixedPhaseData.java:117)
	at main.Main.phaseAndImpute(Main.java:140)
	at main.Main.main(Main.java:110)

  File "/storage/home/leefall2/anaconda3/envs/CKD/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['java', '-Xmx2g', '-jar', '/storage/home/leefall2/anaconda3/envs/CKD/lib/python3.7/site-packages/pypgx/api/beagle.22Jul22.46e.jar', 'gt=/tmp/tmp1zfkzd9c/input.vcf', 'chrom=7:1019834-1032276', 'ref=/storage/home/leefall2/pypgx-bundle/1kgp/GRCh37/CYP2W1.vcf.gz', 'out=/tmp/tmp1zfkzd9c/output', 'impute=false']' returned non-zero exit status 1.

Is there any problem in my data?

I found this kind of case only three times among 7,695 cases.

Best regards,

**Comment by leefall** [comment]
Stargazer worked properly with this case.
Here is the finalized vcf from Stargazer.

#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  971
7       1020320 .       CT      C       .       PASS    PS=C1;VI=unknown_impact;RV=revertant_unknown;SO=unknown_variant;FE=unknown_effect       GT:AD   0/1:3,13
7       1028279 .       G       A       .       PASS    PS=D1;VI=moderate_impact;RV=revertant_false;SO=missense_variant;FE=V432I        GT:AD   0|1:16,16
7       1029860 .       T       C       .       PASS    PS=C1;VI=unknown_impact;RV=revertant_unknown;SO=unknown_variant;FE=unknown_effect       GT:AD   0/1:6,4
7       1032032 .       C       A,G,T   .       PASS    PS=D1;VI=unknown_impact,unknown_impact,unknown_impact;RV=revertant_unknown,revertant_unknown,revertant_unknown;SO=unknown_variant,unknown_variant,unknown_variant;FE=unknown_effect,unknown_effect,unknown_effect       GT:AD   2|0:20,0,17,0

**Comment by sbslee** [comment]
@leefall,

Thanks for reporting the issue. It looks like it's related to #63, but I need more information to be certain. In any case, I'm certain that it's a Beagle problem, not a PyPGx issue. The reason it works fine in Stargazer is because it's running a lower version of Beagle. Read on #63 for more details:

My question to Prof. Browning, the author of Beagle:

> Does this mean that v5.1 is in the wrong and that this bug was fixed in v5.2 (and v5.4) -- i.e. Beagle is supposed to raise this error whenever there is only one marker in a given window?

Prof. Browning's answer:

> You are correct that Beagle is supposed to raise this error whenever there is only one marker in a given window.

That being said, even if Beagle is having troubles processing your VCF, there could be ways to solve the issue within PyPGx. I mean that's exactly what I did in #63. It just means I need to be able to reproduce the error. Could you send me the input VCF file and the exact command line you used? As for the input file, you can even send me the `imported-variants.zip` file (`VcfFrame[Imported]`).

Thanks!

**Comment by sbslee** [comment]
@leefall, 

Here's my email address: sbstevenlee@gmail.com

**Comment by sbslee** [comment]
Closing due to inactivity. Please feel free to re-open it if necessary.
